/**
 * generated by Xtext
 */
package questions.serializer;

import questions.serializer.AbstractQuestionsDSLSemanticSequencer;

@SuppressWarnings("all")
public class QuestionsDSLSemanticSequencer extends AbstractQuestionsDSLSemanticSequencer {
}
