/**
 * generated by Xtext
 */
package questions.serializer;

import questions.serializer.AbstractQuestionsDSLSyntacticSequencer;

@SuppressWarnings("all")
public class QuestionsDSLSyntacticSequencer extends AbstractQuestionsDSLSyntacticSequencer {
}
