/*
 * generated by Xtext
 */
package questions.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class QuestionsDSLUiModule extends questions.ui.AbstractQuestionsDSLUiModule {
	public QuestionsDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
