/**
 * generated by Xtext
 */
package questions.ui.contentassist;

import questions.ui.contentassist.AbstractQuestionsDSLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class QuestionsDSLProposalProvider extends AbstractQuestionsDSLProposalProvider {
}
