/*
* generated by Xtext
*/
package questions;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class QuestionsDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return questions.ui.internal.QuestionsDSLActivator.getInstance().getInjector("questions.QuestionsDSL");
	}
	
}
