/*
 * generated by Xtext
 */
package questions;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QuestionsDSLRuntimeModule extends questions.AbstractQuestionsDSLRuntimeModule {

}
