/*
 * generated by Xtext
 */
package questions.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import questions.ui.internal.QuestionsDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class QuestionsDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return QuestionsDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return QuestionsDSLActivator.getInstance().getInjector(QuestionsDSLActivator.QUESTIONS_QUESTIONSDSL);
	}
	
}
