/*
 * generated by Xtext
 */
package questions.validation

import org.eclipse.xtext.validation.Check
import questions.SingleChoice
import questions.QuestionsPackage
import questions.MultipleChoice

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class QuestionsDSLValidator extends AbstractQuestionsDSLValidator {

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	@Check
	def checkOnlyOne(SingleChoice q) {
		if ( q.answers.filter[isIsCorrect].size != 1 ) {
			error("One and only one answer must be correct", QuestionsPackage.Literals.SINGLE_CHOICE__ANSWERS)
		}
	}
	
	@Check
	def checkAtLeastOne(MultipleChoice q) {
		if ( q.answers.filter[isIsCorrect].size == 0 ) {
			error("At least one answer must be correct", QuestionsPackage.Literals.MULTIPLE_CHOICE__ANSWERS)
		}
	}
}
