/*
* generated by Xtext
*/
package questions.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import questions.services.QuestionsDSLGrammarAccess;

public class QuestionsDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private QuestionsDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected questions.parser.antlr.internal.InternalQuestionsDSLParser createParser(XtextTokenStream stream) {
		return new questions.parser.antlr.internal.InternalQuestionsDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "QuestionSet";
	}
	
	public QuestionsDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(QuestionsDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
